POST http://127.0.0.1:5000/api/v1/rawsparql
Content-Type: application/json

{
    "query": "SELECT ?subject ?predicate ?object WHERE {?subject ?predicate ?object} LIMIT 1000"
}

###
POST http://127.0.0.1:5000/api/v1/rawsparql
Content-Type: application/json

{
    "query": "SELECT ?subject ?predicate ?object WHERE {?subject ?predicate ?object} LIMIT 1O00"
}